name: GitHub workflow

on:
    push:
        branches: [ "main" ]
    #pull_request:
        #branches: [ "main" ]

    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: GitHub workflow
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ vars.HOST }}
                    username: ${{ vars.SSHUSER }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ vars.PORT }}
                    script: |
                        printf "\n\n *** change directory to the project path *** \n\n"
                        cd ${{ vars.PATH }}

                        printf "\n\n *** git status *** \n\n"
                        git status

                        printf "\n\n *** git diff *** \n\n"
                        git diff
                        git checkout -- composer.lock

                        printf "\n\n *** git pull *** \n\n"
                        git pull
                        chown -R ${{ vars.USER }}:www-data ./*
                        chown -R ${{ vars.USER }}:www-data ./.[^.]*

                        printf "\n\n *** composer update *** \n\n"
                        composer update

                        printf "\n\n *** composer dump-autoload *** \n\n"
                        composer dump-autoload -o

                        printf "\n\n *** git status *** \n\n"
                        git status
